# Generated by Django 2.0 on 2017-12-23 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_task_fund'),
    ]

    operations = [
        migrations.AddField(
            model_name='fund',
            name='reference_name',
            field=models.TextField(default=''),
        ),
    ]
